repos:
-   repo: local
    hooks:
    -   id: forbid-to-commit
        name: Don't commit common R artifacts
        entry: Cannot commit .Rhistory, .RData, .Rds or .rds.
        language: fail
        files: '\.(Rhistory|RData|Rds|rds)$'
        # `exclude: <regex>` to allow committing specific files
    -   id: r-lint-custom
        name: R lintr (custom runner)
        entry: bash -lc 'bin/lint.R'
        language: system
        pass_filenames: false


ci:
    autoupdate_schedule: monthly
